-- CreateTable
CREATE TABLE `Mentor` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `phoneNumber` VARCHAR(191) NOT NULL,
    `emailAddress` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `currentJobTitle` VARCHAR(191) NOT NULL,
    `companyName` VARCHAR(191) NOT NULL,
    `experience` ENUM('ONE_THREE_YEARS', 'FOUR_TO_SIX_YEARS', 'SEVEN_TO_TEN_YEARS', 'TEN_YEARS_AND_ABOVE') NOT NULL,
    `expertise` ENUM('FULL_STACK_DEVELOPMENT', 'FRONTEND_DEVELOPMENT', 'BACKEND_DEVELOPMENT', 'UI_UX_DESIGN', 'PRODUCT_MANAGEMENT', 'DIGITAL_MARKETING') NOT NULL,
    `linkedin` VARCHAR(191) NOT NULL,
    `yourWhy` VARCHAR(191) NOT NULL,
    `commitment` ENUM('ONE_HOUR', 'TWO_HOURS', 'THREE_HOURS') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Mentor_emailAddress_key`(`emailAddress`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
